language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.3

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luasocket
  - luarocks install lsocket
  - luarocks install penlight
  - luarocks install cwtest
  - luarocks install lyaml

script:
  - lua src/[bb]/bb_connect/unit_test.lua
